// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/contactocheck/Current.tsx": () => import("../components/mockups/contactocheck/Current.tsx"),
  "./components/mockups/contactocheck/Professional.tsx": () => import("../components/mockups/contactocheck/Professional.tsx")
};
